let produtosJson = [
    { id: 1, type: 'carne', name: 'Big Mac', img: 'img/MC/carne-bovina/big-mac.png', kc: '499 kcal', price: 20.00, description: 'Dois hambúrgueres (100% carne bovina), alface americana, queijo sabor cheddar, molho especial, cebola, picles e pão com gergelim.' },
    { id: 2, type: 'carne', name: 'Cheddar McMelt', img: 'img/MC/carne-bovina/cheddar-mcmelt.png', kc: '855 kcal', price: 25.00, description: 'Dois hambúrgueres (100% carne bovina), molho lácteo cremoso sabor cheddar, cebola ao molho shoyu e pão escuro com gergelim.' },
    { id: 3, type: 'carne', name: 'CheeseBurger', img: 'img/MC/carne-bovina/cheeseburger.png', kc: '297.7 kcal', price: 25.00, description: 'Um hamburguer (100% carne bovina), queijo sabor cheddar, cebola, picles, ketchup, mostarda e pão sem gergelim.' },
    { id: 4, type: 'carne', name: 'Duplo burger bacon', img: 'img/MC/carne-bovina/duplo-burger-bacon.png', kc: '478 kcal', price: 23.00, description: 'Dois hambúrgueres (100% carne bovina), queijo sabor cheddar, cebola, fatias de bacon, ketchup, mostarda e pão com gergelim.' },
    { id: 5, type: 'carne', name: 'Duplo burger com queijo', img: 'img/MC/carne-bovina/duplo-burger-com-queijo.png', kc: '478 kcal', price: 20.00, description: 'Dois hambúrgueres, uma explosão de sabor. Dois deliciosos hambúrgueres de carne 100% bovina, queijo sabor cheddar derretido, picles, cebola picada, ketchup, mostarda e pão com gergelim.' },
    { id: 6, type: 'carne', name: 'Duplo cheddar McMelt', img: 'img/MC/carne-bovina/duplo-cheddar.png', kc: '855 kcal', price: 27.00, description: 'Dois hambúrgueres (100% carne bovina), molho lácteo cremoso sabor cheddar, cebola ao molho shoyu e pão escuro com gergelim.' },
    { id: 7, type: 'carne', name: 'Duplo quarterão', img: 'img/MC/carne-bovina/duplo-quarterao.png', kc: '819 kcal', price: 25.50, description: 'Dois hambúrgueres (100% carne bovina), mostarda, ketchup, cebola, queijo sabor cheddar e pão com gergelim.' },
    { id: 8, type: 'carne', name: 'Hamburger', img: 'img/MC/carne-bovina/hamburger.png', kc: '249.1 kcal', price: 14.00, description: 'Um Hamburguer (100% carne bovina), cebola, picles, ketchup, mostarda e pão sem gergelim.' },
    { id: 9, type: 'carne', name: 'Mc Fiesta', img: 'img/MC/carne-bovina/mc-fiesta.png', kc: '271 kcal', price: 24.00, description: 'Pão sem gergelim, hambúrguer de carne 100% bovina, alface, tomate e molho tasty (molho emulsionado sabor carne grelhada).' },
    { id: 10, type: 'carne', name: 'Mc nifico bacon', img: 'img/MC/carne-bovina/mc-nifico-bacon.png', kc: '271 kcal', price: 21.00, description: 'Pão sem gergelim, hambúrguer de carne 100% bovina, alface, tomate e molho tasty (molho emulsionado sabor carne grelhada).' },
    { id: 11, type: 'carne', name: 'Quarterão com queijo', img: 'img/MC/carne-bovina/quarterao-com-queijo.png', kc: '549 kcal', price: 20.00, description: 'Um hambúrguer (100% carne bovina), queijo sabor cheddar, picles, cebola, ketchup, mostarda e pão com gergelim.' },
    { id: 12, type: 'carne', name: 'Triplo burger', img: 'img/MC/carne-bovina/triplo-burger.png', kc: '545 kcal', price: 30.00, description: 'Três hambúrgueres (100% carne bovina), queijo sabor cheddar, cebola, picles, ketchup, mostarda e pão com gergelim.' },

    { id: 13, type: 'frango', name: 'Chicken Jr.', img: 'img/MC/frango/chickenJr.png', kc: '342.5 kcal', price: 25.00, description: 'Frango empanado, maionese, alface americana e pão com gergelim.' },
    { id: 14, type: 'frango', name: 'Mc Chicken Bacon', img: 'img/MC/frango/mcchicken-bacon.png', kc: '448 kcal', price: 21.00, description: 'Frango empanado, maionese, bacon, alface americana e pão com gergelim.' },
    { id: 15, type: 'frango', name: 'Mc Chicken', img: 'img/MC/frango/mcchicken.png', kc: '396 kcal', price: 19.00, description: 'Frango empanado, maionese, alface americana e pão com gergelim.' },
    { id: 16, type: 'frango', name: 'Mc Crispy Deluxe', img: 'img/MC/frango/mccrispy-deluxe.png', kc: '625 kcal', price: 20.00, description: 'Sanduiche composto por tipo brioche com batata, carne 100% de peito de frango, temperada e empanada, maionese, alface americana e tomate.' },
    { id: 17, type: 'frango', name: 'Mc Crispy Melt and bacon', img: 'img/MC/frango/mccrispy-melt-and-bacon.png', kc: '628 kcal', price: 25.00, description: 'Sanduiche composto por pão tipo brioche com batata, carne 100% de peito de frango, temperada e empanada, molho lácteo cremoso sabor cheddar e fatias de bacon.' },
    { id: 18, type: 'frango', name: 'Mc Crispy Legend', img: 'img/MC/frango/mccrispy.png', kc: '926 kcal', price: 30.00, description: 'Composto por pão tipo brioche com batata, molho do CBO, cebola crispy, bacon em fatias, alface americana, queijo sabor cheddar e carne 100% de peito de frango, temperada e empanada.' },


    { id: 3, type: 'acompanhamentos', name: 'McFritas Cheddar Bacon', img: 'img/MC/acompanhamentos/mcFritas-cheddar-bacon.png', kc: '525 kcal', price: 15.00, description: 'A batata frita mais famosa do mundo, agora com melt sabor cheddar e bacon crispy. Não dá para resistir, experimente!' },

    { id: 4, type: 'bebidas-frias', name: 'Coca Cola 300mL', img: 'img/MC/bebidas-frias/coca-cola-300ml.png', kc: '129 kcal', price: 12.00, description: 'Refrescante e geladinho. Uma bebida assim refresca a vida. Você pode escolher entre Coca-Cola, Coca-Cola Zero, Fanta Guaraná e Fanta Laranja.' },
]